### ISSUE TITLE
Read function

### ISSUE THREAD

**Issue by dsteinel** [nneves/Raspberrypi_GPIO#4]
Hey,

i have an issue with reading the values of the pins. I have a simple setup: one LED and one BUTTON. The LED works perfectly fine with the webinterface. But now the interface should react either the button is pressed or not.

I would be really glad if someone could publish a "read Input" sample.

**Comment by nneves** [comment]
Well, that was @mikedevita request a few months ago, it shouldn't be to difficult for socket.io (WebSockets) mode, for standard REST interface it's tricky (just gives a bit more work) ... let me see if I can get some time (pretty difficult at the time being, really really busy at work)...

Could you please ping me if this case gets forgotten, say about in 1 to 2 weeks max time? Sorry about this, I really like to help out.

**Comment by dsteinel** [comment]
I will do so. Thanks!

p.s.
I just need the websocket mode ...

**Comment by mikedevita** [comment]
I had something setup using @balderdashy/sails but the backend ended up still using this library to communicate.

**Comment by nneves** [comment]
Closing this issue, no time available to fix old projects!
